# -*- coding: utf-8 -*-
"""Medagent.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rMl3wsOsIzpC9TNbPbBSLqIBugTV3p0s

Dataset
"""

from google.colab import drive
drive.mount('/content/drive')

import json
import os
import time
from dataclasses import dataclass, asdict
from typing import List, Dict, Any, Optional
import numpy as np # Import numpy

# ==========================================
# 1. DATA STRUCTURES & SCHEMAS
# ==========================================

@dataclass
class MedicalCase:
    case_id: str
    dataset_name: str
    case_text: str
    options: Optional[Dict[str, str]]  # e.g., {"A": "...", "B": "..."}
    evidence_context: Optional[str]    # e.g., PubMed Abstract
    gold_label: str

@dataclass
class AgentOutput:
    final_answer: str
    confidence: float
    diagnosis_or_hypothesis: List[str]
    reasoning: str
    cited_evidence: List[str]
    missing_evidence: List[str]
    safety_concerns: List[str]
    revision_note: Optional[str] = None

@dataclass
class ExecutionTrace:
    case_id: str
    architecture: str
    round_1_outputs: Dict[str, Any]  # Maps agent_id -> parsed schema
    round_2_outputs: Dict[str, Any]  # Maps agent_id -> parsed schema (Empty for CoT)
    aggregated_answer: str
    total_tokens_used: int
    estimated_cost: float

# ==========================================
# 2. LLM CLIENT WRAPPER
# ==========================================

class MedicalLLMClient:
    def __init__(self, model_name: str = "gpt-4o", temperature: float = 0.4):
        self.model_name = model_name
        self.temperature = temperature
        # Real pricing: gpt-4o-2024-05-13 approx values
        self.input_token_cost = 5.00 / 1000000
        self.output_token_cost = 15.00 / 1000000

    def _get_system_prompt(self) -> str:
        return """You are an expert, board-certified clinical AI assistant.
Your analysis must be evidence-grounded, rigorous, and highly attentive to patient safety.
You MUST respond strictly with a valid JSON object matching the requested schema. Do not include markdown formatting like ```json or any trailing text."""

    def _get_schema_instructions(self) -> str:
        return """
Output MUST strictly follow this JSON structure:
{
  "final_answer": "Your final chosen option",
  "confidence": 0.85,
  "diagnosis_or_hypothesis": ["Primary Diagnosis"],
  "reasoning": "Clinical rationale...",
  "cited_evidence": ["Fact from case"],
  "missing_evidence": ["Required data"],
  "safety_concerns": ["Risks"],
  "revision_note": null
}"""

    def call_agent(self, user_prompt: str, agent_role: str = "Generalist Clinical Agent") -> tuple[Dict[str, Any], int]:
        full_system_prompt = f"{self._get_system_prompt()}\nYour Role: {agent_role}\n{self._get_schema_instructions()}"

        # Use the real API call logic
        try:
            parsed_output, tokens = call_real_llm(full_system_prompt, user_prompt, model=self.model_name)
            return parsed_output, tokens
        except Exception as e:
            print(f"API Error, falling back to mock: {e}")
            # Fallback mock for stability if API fails
            mock_resp = {"final_answer": "A", "confidence": 0.0, "reasoning": "Error Fallback"}
            return mock_resp, 0

    def call_free_form_llm(self, system_prompt: str, user_prompt: str) -> tuple[str, int]:
        """Makes a raw LLM call without schema enforcement, returns raw text and tokens."""
        try:
            raw_text, tokens = call_real_llm(system_prompt, user_prompt, model=self.model_name)
            # Ensure raw_text is a string, not a parsed JSON if call_real_llm auto-parses
            if isinstance(raw_text, dict): # If call_real_llm returns a dict, convert it to string
                raw_text = json.dumps(raw_text)
            return raw_text, tokens
        except Exception as e:
            print(f"Free-form API Error: {e}")
            return "ERROR_LLM_CALL", 0

# ==========================================
# 3. ARCHITECTURE PIPELINES
# ==========================================

class AuditPipelineOrchestrator:
    def __init__(self, client: MedicalLLMClient):
        self.client = client

    def _build_case_prompt(self, case: MedicalCase) -> str:
        prompt = f"### CLINICAL CASE CONTEXT\n{case.case_text}\n\n"
        if case.evidence_context:
            prompt += f"### GROUNDING EVIDENCE/ABSTRACT\n{case.evidence_context}\n\n"
        if case.options:
            prompt += f"### OPTIONS\n"
            if isinstance(case.options, dict):
                for key, val in case.options.items():
                    prompt += f"{key}: {val}\n"
            elif isinstance(case.options, list):
                for option_val in case.options:
                    prompt += f"- {option_val}\n"
            else: # Fallback for unexpected types
                prompt += f"{case.options}\n"
        return prompt

    def run_single_agent_cot(self, case: MedicalCase) -> ExecutionTrace:
        user_prompt = self._build_case_prompt(case)
        user_prompt += "\nPerform a systematic clinical evaluation. Detail your reasoning and commit to a final answer."
        parsed_json, tokens = self.client.call_agent(user_prompt, agent_role="Single-Agent CoT")
        cost = tokens * self.client.output_token_cost
        return ExecutionTrace(case.case_id, "Single-Agent CoT", {"Agent_Primary": parsed_json}, {}, parsed_json.get("final_answer", "UNKNOWN"), tokens, cost)

    def independent_vote(self, case: MedicalCase) -> ExecutionTrace:
        agent_ids = ["Agent_Alpha", "Agent_Beta", "Agent_Gamma"]
        results = {}
        total_tokens = 0 # Initialize total_tokens
        base_case_prompt = self._build_case_prompt(case)
        r1_prompt= base_case_prompt + "\nPerform a systematic clinical evaluation. Detail your reasoning and commit to a final answer."

        for agent in agent_ids:
            out, tokens = self.client.call_agent(r1_prompt, agent_role=f"Symmetric Debater ({agent})")
            results[agent] = out
            total_tokens += tokens
        votes = [results[a].get("final_answer") for a in agent_ids]
        final_vote= max(set(votes), key=votes.count)
        cost= total_tokens*self.client.output_token_cost
        return ExecutionTrace(case.case_id, "Independent Vote", results, {}, final_vote, total_tokens, cost)

    def run_symmetric_debate(self, case: MedicalCase) -> ExecutionTrace:
        agent_ids = ["Agent_Alpha", "Agent_Beta", "Agent_Gamma"]
        base_case_prompt = self._build_case_prompt(case)
        total_tokens = 0
        r1_results, r2_results = {}, {}

        r1_prompt = base_case_prompt + "\nAnalyze the case independently."
        for agent in agent_ids:
            out, tokens = self.client.call_agent(r1_prompt, agent_role=f"Symmetric Debater ({agent})")
            r1_results[agent] = out
            total_tokens += tokens

        peer_insights = "### ANONYMOUS PEER RATIONALES\n"
        for p_id, p_data in r1_results.items():
            peer_insights += f"- Answer: {p_data.get('final_answer')}. Rationale: {p_data.get('reasoning')}\n"

        for agent in agent_ids:
            r2_prompt = base_case_prompt + f"\n{peer_insights}\nCritique peer perspectives and finalize your answer."
            out, tokens = self.client.call_agent(r2_prompt, agent_role=f"Symmetric Debater ({agent})")
            r2_results[agent] = out
            total_tokens += tokens

        r2_votes = [r2_results[a].get("final_answer") for a in agent_ids]
        final_agg = max(set(r2_votes), key=r2_votes.count)
        cost = total_tokens * self.client.output_token_cost
        return ExecutionTrace(case.case_id, "Symmetric Debate", r1_results, r2_results, final_agg, total_tokens, cost)

    def run_role_specialist_board(self, case: MedicalCase) -> ExecutionTrace:
        roles = {
            "Agent_Diagnostician": "Diagnostician (focus on identifying the primary condition)",
            "Agent_Evidence": "Evidence/Pathophysiology Reviewer (focus on clinical mechanisms and grounding)",
            "Agent_Treatment": "Treatment/Safety Specialist (focus on management and contraindications)"
        }
        base_prompt = self._build_case_prompt(case)
        r1_results, r2_results = {}, {}
        total_tokens = 0

        # Round 1: Initial specialized analysis
        for agent_id, role_desc in roles.items():
            out, tokens = self.client.call_agent(base_prompt + f"\nAnalyze from your specific perspective: {role_desc}", agent_role=role_desc)
            r1_results[agent_id] = out
            total_tokens += tokens

        # Round 2: Final revision after seeing peers
        peer_context = "\n".join([f"- {role}: {data.get('reasoning')}" for role, data in r1_results.items()])
        final_prompt = base_prompt + f"\n### PEER SPECIALIST INSIGHTS\n{peer_context}\nFinalize the diagnosis and treatment plan."

        for agent_id, role_desc in roles.items():
            out, tokens = self.client.call_agent(final_prompt, agent_role=role_desc)
            r2_results[agent_id] = out
            total_tokens += tokens

        votes = [r2_results[a].get("final_answer") for a in roles]
        final_agg = max(set(votes), key=votes.count)
        return ExecutionTrace(case.case_id, "Role-Specialist Board", r1_results, r2_results, final_agg, total_tokens, total_tokens * self.client.output_token_cost)

    def run_critic_reviewer_board(self, case: MedicalCase) -> ExecutionTrace:
        solvers = ["Solver_A", "Solver_B"]
        base_prompt = self._build_case_prompt(case)
        total_tokens = 0
        r1_results, r2_results = {}, {}

        # Round 1: Initial Solvers
        for s_id in solvers:
            out, tokens = self.client.call_agent(base_prompt, agent_role="Clinical Solver")
            r1_results[s_id] = out
            total_tokens += tokens

        # Critic Analysis
        critic_prompt = base_prompt + "\n### PROPOSED SOLUTIONS\n" + "\n".join([f"- {s}: {r1_results[s].get('reasoning')}" for s in solvers])
        critic_prompt += "\nIdentify contradictions, unsupported claims, or missing evidence."
        critic_out, c_tokens = self.client.call_agent(critic_prompt, agent_role="Skeptical Clinical Reviewer")
        total_tokens += c_tokens

        # Round 2: Revisions based on critique
        revision_prompt = base_prompt + f"\n### CRITIC REVIEW\n{critic_out.get('reasoning')}\nRevise your initial answer."
        for s_id in solvers:
            out, tokens = self.client.call_agent(revision_prompt, agent_role="Clinical Solver (Revised)")
            r2_results[s_id] = out
            total_tokens += tokens

        # Reviewer breaks tie or selects best
        final_votes = [r2_results[s].get("final_answer") for s in solvers]
        final_agg = final_votes[0] if len(set(final_votes)) == 1 else critic_out.get("final_answer", final_votes[0])
        return ExecutionTrace(case.case_id, "Critic-Reviewer Board", r1_results, r2_results, final_agg, total_tokens, total_tokens * self.client.output_token_cost)

    def run_workflow_orchestrator(self, case: MedicalCase) -> ExecutionTrace:
        base_prompt = self._build_case_prompt(case)
        total_tokens = 0

        # Step 1: Evidence Extraction
        extractor_prompt = base_prompt + "\nExtract only relevant clinical evidence and facts from the text."
        extraction, t1 = self.client.call_agent(extractor_prompt, agent_role="Evidence Extractor")
        total_tokens += t1

        # Step 2: Diagnostic Solving
        solver_prompt = f"### EXTRACTED EVIDENCE\n{extraction.get('cited_evidence')}\n{base_prompt}\nSolve the case."
        final_out, t2 = self.client.call_agent(solver_prompt, agent_role="Diagnostic Solver")
        total_tokens += t2

        return ExecutionTrace(case.case_id, "Workflow-Orchestrator", {"Extractor": extraction}, {"Solver": final_out}, final_out.get("final_answer"), total_tokens, total_tokens * self.client.output_token_cost)

def save_trace_to_jsonl(trace: ExecutionTrace, output_path: str):
    with open(output_path, "a", encoding="utf-8") as f:
        f.write(json.dumps(asdict(trace)) + "\n")

"""# New Section"""

import openai
from google.colab import userdata
import json

# OpenRouter configuration
OPENROUTER_API_KEY = userdata.get('OPENROUTER_API_KEY')
OR_CLIENT = openai.OpenAI(
  base_url="https://openrouter.ai/api/v1",
  api_key=OPENROUTER_API_KEY,
)

def call_real_llm(system_prompt, user_prompt, model="openai/gpt-4o-mini"):
    """
    Implementation for OpenRouter API calls.
    Defaulting to a cost-effective model, but you can change this to any
    OpenRouter supported ID (e.g., 'openai/gpt-4o').
    """
    response = OR_CLIENT.chat.completions.create(
      extra_headers={
        "HTTP-Referer": "https://colab.research.google.com/", # Optional, for OpenRouter rankings
        "X-Title": "Medical Agent Audit", # Optional
      },
      model=model,
      messages=[
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt}
      ],
      response_format={ "type": "json_object" },
      temperature=0.4
    )

    raw_text = response.choices[0].message.content
    usage = response.usage.total_tokens
    return json.loads(raw_text), usage

print("OpenRouter client initialized. Your MedicalLLMClient will now use this function.")

from google.colab import drive
import pandas as pd
import numpy as np
import json

# Mount drive

def load_qa_dataset(path='/content/drive/MyDrive/QA_data.json'):
    """Loads data from your specific JSON format."""
    with open(path, 'r') as f:
        data = json.load(f)

    cases = []
    for item in data:
        # Your format uses 'answer' string like 'A. IGF1', we need the index 'A'
        gold_label = item.get('answer', ' ')[0]

        cases.append(MedicalCase(
            case_id=str(item.get('Index')),
            dataset_name="Drive_QA",
            case_text=item.get('question'),
            options=None, # Options are already in the question text for this format
            evidence_context=" ".join(item.get('Scoring_Points', [])),
            gold_label=gold_label
        ))
    return cases

def load_pubmedqa_dataset(questions_path='ori_pqal.json', ground_truth_path='test_ground_truth.json'):
    """Loads PubMedQA data from JSON files."""
    with open(questions_path, 'r') as f_q:
        questions_data = json.load(f_q)

    with open(ground_truth_path, 'r') as f_gt:
        ground_truth_data = json.load(f_gt)

    cases = []
    for q_id, q_info in questions_data.items():
        gold_label = ground_truth_data.get(q_id)
        if gold_label is None:
            # Skip if no ground truth for this question
            continue

        cases.append(MedicalCase(
            case_id=str(q_id),
            dataset_name="PubMedQA",
            case_text=q_info.get('QUESTION'),
            options=["yes","no","maybe"], # PubMedQA is typically yes/no/maybe, handled by gold_label
            evidence_context=" ".join(q_info.get('CONTEXTS', [])),
            gold_label=gold_label
        ))
    return cases

class MedicalAuditEvaluator:
    """
    Implementation of Core Metrics for Multi-Agent Clinical Analysis.
    """

    # CARA LLM Constants
    _CARA_SYSTEM_PROMPT = """You are an expert evaluator assessing the reasoning alignment between two AI medical agents.\n\nYou will be given:\n1. A medical question with answer choices\n2. The reasoning traces from two agents (they may or may not have selected the same final answer)\n\nYour task: Rate how well the two agents' reasoning processes align with each other on a scale from 1 to 5.\n\nScoring rubric:\n- 5 (Perfect alignment): Both agents follow essentially the same reasoning path, cite the same medical facts, and reach the answer through identical logic.\n- 4 (Strong alignment): Both agents share the core reasoning pathway with minor differences in emphasis or supporting details.\n- 3 (Moderate alignment): The agents share some reasoning elements but take partially different paths. Some overlap, some divergence.\n- 2 (Weak alignment): The agents reason through substantially different paths. Different medical facts, different logical chains, minimal overlap.\n- 1 (No alignment / Contradictory): The agents' reasoning contradicts each other, or they rely on completely incompatible explanations.\n\nYour response must be a JSON object with a 'SCORE' field (integer 1-5) and a 'JUSTIFICATION' field (1-2 sentences). Do not include any other text or markdown formatting.\nExample:\n{\n  "SCORE": 3,\n  "JUSTIFICATION": "Both agents considered patient history but diverged on treatment options."
}"""

    _CARA_USER_TEMPLATE_AGREE = """## Medical Question\n{question_text}\n\n## Gold Answer\n{gold_answer}\n\n## Agents' Shared Answer\n{majority_answer}\n\n## Agent A Reasoning ({agent_a_id})\n{agent_a_reasoning}\n\n## Agent B Reasoning ({agent_b_id})\n{agent_b_reasoning}\n\nRate the reasoning alignment between Agent A and Agent B (1-5):"""

    _CARA_USER_TEMPLATE_DISAGREE = """## Medical Question\n{question_text}\n\n## Gold Answer\n{gold_answer}\n\n## Agent A Answer: {answer_a}\n## Agent A Reasoning ({agent_a_id})\n{agent_a_reasoning}\n\n## Agent B Answer: {answer_b}\n## Agent B Reasoning ({agent_b_id})\n{agent_b_reasoning}\n\nRate the reasoning alignment between Agent A and Agent B (1-5):"""

    MAX_RETRIES = 3
    RETRY_DELAY = 5 # seconds
    NUM_CARA_RUNS = 3 # score each pair N times, take mean

    def __init__(self):
        self.results = []
        self.llm_client_for_cara = MedicalLLMClient(model_name="openai/gpt-4o-mini", temperature=0.0) # Dedicated client for deterministic CARA calls

    def _parse_cara_response(self, text: str) -> tuple:
        """Parse SCORE and JUSTIFICATION from LLM response."""
        try:
            parsed_json = json.loads(text)
            score = parsed_json.get('SCORE')
            justification = parsed_json.get('JUSTIFICATION', '')
            if score is None or not isinstance(score, int) or score < 1 or score > 5:
                return None, f"Failed to parse valid score from JSON: {text}"
            return score, justification
        except json.JSONDecodeError:
            return None, f"Failed to decode JSON from response: {text[:200]}"

    def _build_cara_user_prompt(self, case: MedicalCase, agent_a_id: str, agent_a_output: Dict[str, Any], agent_b_id: str, agent_b_output: Dict[str, Any]) -> str:
        agent_a_reasoning_steps = agent_a_output.get('reasoning', '').split('\n') if agent_a_output.get('reasoning') else []
        agent_b_reasoning_steps = agent_b_output.get('reasoning', '').split('\n') if agent_b_output.get('reasoning') else []

        agent_a_reasoning_formatted = "\n".join(f"  {i+1}. {step}" for i, step in enumerate(agent_a_reasoning_steps))
        agent_b_reasoning_formatted = "\n".join(f"  {i+1}. {step}" for i, step in enumerate(agent_b_reasoning_steps))

        is_disagree = agent_a_output.get('final_answer') != agent_b_output.get('final_answer')

        if is_disagree:
            return self._CARA_USER_TEMPLATE_DISAGREE.format(
                question_text=case.case_text,
                gold_answer=case.gold_label,
                answer_a=agent_a_output.get('final_answer'),
                agent_a_id=agent_a_id,
                agent_a_reasoning=agent_a_reasoning_formatted,
                answer_b=agent_b_output.get('final_answer'),
                agent_b_id=agent_b_id,
                agent_b_reasoning=agent_b_reasoning_formatted,
            )
        else:
            return self._CARA_USER_TEMPLATE_AGREE.format(
                question_text=case.case_text,
                gold_answer=case.gold_label,
                majority_answer=agent_a_output.get('final_answer'), # Or agent_b_output.get('final_answer'), as they agree
                agent_a_id=agent_a_id,
                agent_a_reasoning=agent_a_reasoning_formatted,
                agent_b_id=agent_b_id,
                agent_b_reasoning=agent_b_reasoning_formatted,
            )

    def _call_cara_llm_once(self, case: MedicalCase, agent_a_id: str, agent_a_output: Dict[str, Any], agent_b_id: str, agent_b_output: Dict[str, Any]) -> dict:
        user_prompt = self._build_cara_user_prompt(case, agent_a_id, agent_a_output, agent_b_id, agent_b_output)

        for attempt in range(self.MAX_RETRIES):
            try:
                text, tokens_used = self.llm_client_for_cara.call_free_form_llm(self._CARA_SYSTEM_PROMPT, user_prompt)
                score, justification = self._parse_cara_response(text)

                if score is None:
                    # log.warning(f"  CARA: parse error (attempt {attempt+1}): {justification}")
                    if attempt < self.MAX_RETRIES - 1:
                        time.sleep(self.RETRY_DELAY)
                        continue
                    return {"score": None, "justification": justification, "raw": text, "usage": {"tokens": tokens_used}, "error": "parse_failed"}

                return {"score": score, "justification": justification, "usage": {"tokens": tokens_used}, "error": None}

            except Exception as e:
                # log.warning(f"  CARA: API error (attempt {attempt+1}): {e}")
                if attempt < self.MAX_RETRIES - 1:
                    time.sleep(self.RETRY_DELAY * (attempt + 1))
                else:
                    return {"score": None, "justification": "", "usage": {"tokens": tokens_used}, "error": str(e)}

    def run_cara_llm_evaluation(self, case: MedicalCase, trace: ExecutionTrace) -> dict:
        # CARA LLM is designed for comparing two agents. We'll take the first two agents
        # from Round 1 outputs if available.
        agent_ids = list(trace.round_1_outputs.keys())
        if len(agent_ids) < 2:
            # If less than 2 agents, CARA LLM comparison is not applicable.
            return {"cara_llm_score": None, "cara_llm_sd": None, "cara_llm_cost": 0, "n_cara_runs": 0}

        agent_a_id = agent_ids[0]
        agent_b_id = agent_ids[1]
        agent_a_output = trace.round_1_outputs[agent_a_id]
        agent_b_output = trace.round_1_outputs[agent_b_id]

        scores = []
        total_cara_tokens = 0

        for run_idx in range(self.NUM_CARA_RUNS):
            res = self._call_cara_llm_once(case, agent_a_id, agent_a_output, agent_b_id, agent_b_output)
            if res["score"] is not None:
                scores.append(res["score"])
            total_cara_tokens += res["usage"].get("tokens", 0)

        if scores:
            mean_score = np.mean(scores)
            sd_score = np.std(scores) if len(scores) > 1 else 0.0
            cost = total_cara_tokens * self.llm_client_for_cara.output_token_cost
            return {
                "cara_llm_score": round(mean_score, 4),
                "cara_llm_sd": round(sd_score, 4),
                "cara_llm_cost": cost,
                "n_cara_runs": len(scores)
            }
        else:
            return {"cara_llm_score": None, "cara_llm_sd": None, "cara_llm_cost": total_cara_tokens * self.llm_client_for_cara.output_token_cost, "n_cara_runs": 0}

    def calculate_metrics(self, trace: ExecutionTrace, gold_label: str):
        """Processes a single trace to compute metrics."""
        # 1. Final Accuracy
        is_correct = trace.aggregated_answer.strip().startswith(gold_label)

        # 2. Answer Agreement (Round 1 vs Round 2)
        r1_answers = [out.get('final_answer', '') for out in trace.round_1_outputs.values()]
        r2_answers = [out.get('final_answer', '') for out in trace.round_2_outputs.values()]

        def get_agreement(answers):
            if not answers: return 1.0
            pairs = 0
            matches = 0
            for i in range(len(answers)):
                for j in range(i + 1, len(answers)):
                    pairs += 1
                    if answers[i] == answers[j]: matches += 1
            return matches / pairs if pairs > 0 else 1.0

        agreement_r1 = get_agreement(r1_answers)
        agreement_r2 = get_agreement(r2_answers) if r2_answers else agreement_r1

        # 3. Evidence Overlap (Simple F1 between agents)
        all_evidence = [set(out.get('cited_evidence', [])) for out in trace.round_1_outputs.values()]
        # Simplified: Average pairwise Jaccard similarity as overlap proxy
        overlaps = []
        for i in range(len(all_evidence)):
            for j in range(i + 1, len(all_evidence)):
                union = len(all_evidence[i] | all_evidence[j])
                intersection = len(all_evidence[i] & all_evidence[j])
                overlaps.append(intersection / union if union > 0 else 1.0)
        avg_evidence_overlap = np.mean(overlaps) if overlaps else 1.0

        # 4. Revision Utility
        utility = 0
        # Only calculate if there are round_2_outputs and the set of agent IDs in both rounds are the same
        if trace.round_2_outputs and set(trace.round_1_outputs.keys()) == set(trace.round_2_outputs.keys()):
            for agent_id in trace.round_1_outputs:
                r1_correct = trace.round_1_outputs[agent_id].get('final_answer', '').strip().startswith(gold_label)
                r2_correct = trace.round_2_outputs[agent_id].get('final_answer', '').strip().startswith(gold_label)
                if not r1_correct and r2_correct: utility += 1
                if r1_correct and not r2_correct: utility -= 1

        # 5. Confidence Calibration
        confidences = [out.get('confidence', 0) for out in trace.round_1_outputs.values()]
        avg_conf = np.mean(confidences)

        # 6. CARA LLM Evaluation (Reasoning Alignment)
        # Note: The cara_llm_score, sd, and cost are now being passed in from the orchestrator loop.
        # This method's purpose is to calculate *metrics from the trace itself*, not to run LLM calls.

        metrics = {
            "case_id": trace.case_id,
            "correct": is_correct,
            "agreement_r1": agreement_r1,
            "agreement_r2": agreement_r2,
            "evidence_overlap": avg_evidence_overlap,
            "revision_utility": utility,
            "avg_confidence": avg_conf,
            "cara_llm_score": None, # These will be overwritten by the orchestrator after this call.
            "cara_llm_sd": None,
            "cara_llm_cost": 0,
            "cost": trace.estimated_cost
        }
        self.results.append(metrics)
        return metrics

    def get_summary(self):
        df = pd.DataFrame(self.results)
        summary = {
            "Mean Accuracy": df['correct'].mean(),
            "Consensus Shift": df['agreement_r2'].mean() - df['agreement_r1'].mean(),
            "Avg Evidence Overlap": df['evidence_overlap'].mean(),
            "Total Revision Utility": df['revision_utility'].sum(),
            "Mean CARA LLM Score": df['cara_llm_score'].mean() if 'cara_llm_score' in df.columns else None,
            "Total CARA LLM Cost": df['cara_llm_cost'].sum() if 'cara_llm_cost' in df.columns else 0,
            "Total Cost": df['cost'].sum()
        }
        return summary

import pandas as pd

try:
    cases = load_qa_dataset()[:30]  # Testing first 2 cases
    llm_client = MedicalLLMClient(model_name="openai/gpt-4o-mini")
    orchestrator = AuditPipelineOrchestrator(llm_client)

    # Initialize evaluators for all architectures
    evaluators = {
        "Single-Agent CoT": MedicalAuditEvaluator(),
        "Independent Vote": MedicalAuditEvaluator(),
        "Symmetric Debate": MedicalAuditEvaluator(),
        "Role-Specialist Board": MedicalAuditEvaluator(),
        "Critic-Reviewer Board": MedicalAuditEvaluator(),
        "Workflow-Orchestrator": MedicalAuditEvaluator()
    }

    architectures = [
        ("Single-Agent CoT", orchestrator.run_single_agent_cot),
        ("Independent Vote", orchestrator.independent_vote),
        ("Symmetric Debate", orchestrator.run_symmetric_debate),
        ("Role-Specialist Board", orchestrator.run_role_specialist_board),
        ("Critic-Reviewer Board", orchestrator.run_critic_reviewer_board),
        ("Workflow-Orchestrator", orchestrator.run_workflow_orchestrator)
    ]

    for name, func in architectures:
        print(f"\n--- Running {name} ---")
        for case in cases:
            print(f"Processing Case {case.case_id}...")
            trace = func(case)

            # Run CARA LLM evaluation for agent pairs within the trace if applicable
            cara_res = evaluators[name].run_cara_llm_evaluation(case, trace) # Pass full MedicalCase

            metrics = evaluators[name].calculate_metrics(trace, case.gold_label)
            metrics["cara_llm_score"] = cara_res["cara_llm_score"]
            metrics["cara_llm_sd"] = cara_res["cara_llm_sd"]
            metrics["cara_llm_cost"] = cara_res["cara_llm_cost"]

    # Display summaries
    summary_data = []
    for name, eval_obj in evaluators.items():
        res = eval_obj.get_summary()
        res['Architecture'] = name
        summary_data.append(res)

    summary_df = pd.DataFrame(summary_data).set_index('Architecture')
    display(summary_df)

except Exception as e:
    print(f"Error: {e}")

"""### PubMedQA Evaluation

Now, let's run the same evaluation pipelines on the PubMedQA dataset. Please ensure `ori_pqal.json` and `test_ground_truth.json` are accessible (e.g., uploaded to your Colab environment or mounted Google Drive).
"""

try:
    # Adjust paths if files are in Google Drive
    # For example: '/content/drive/MyDrive/ori_pqal.json'
    pubmedqa_cases = load_pubmedqa_dataset(
        questions_path='/content/drive/MyDrive/ori_pqal.json',
        ground_truth_path='/content/drive/MyDrive/test_ground_truth.json'
    )[:2] # Testing first 2 cases for PubMedQA

    llm_client_pubmedqa = MedicalLLMClient(model_name="openai/gpt-4o-mini")
    orchestrator_pubmedqa = AuditPipelineOrchestrator(llm_client_pubmedqa)

    evaluators_pubmedqa = {
        "Single-Agent CoT": MedicalAuditEvaluator(),
        "Independent Vote": MedicalAuditEvaluator(),
        "Symmetric Debate": MedicalAuditEvaluator(),
        "Role-Specialist Board": MedicalAuditEvaluator(),
        "Critic-Reviewer Board": MedicalAuditEvaluator(),
        "Workflow-Orchestrator": MedicalAuditEvaluator()
    }

    architectures_pubmedqa = [
        ("Single-Agent CoT", orchestrator_pubmedqa.run_single_agent_cot),
        ("Independent Vote", orchestrator_pubmedqa.independent_vote),
        ("Symmetric Debate", orchestrator_pubmedqa.run_symmetric_debate),
        ("Role-Specialist Board", orchestrator_pubmedqa.run_role_specialist_board),
        ("Critic-Reviewer Board", orchestrator_pubmedqa.run_critic_reviewer_board),
        ("Workflow-Orchestrator", orchestrator_pubmedqa.run_workflow_orchestrator)
    ]

    print("\n--- Running PubMedQA Evaluation ---")
    for name, func in architectures_pubmedqa:
        print(f"\n--- Running {name} for PubMedQA ---")
        for case in pubmedqa_cases:
            print(f"Processing PubMedQA Case {case.case_id}...")
            trace = func(case)

            # Run CARA LLM evaluation for agent pairs within the trace if applicable
            cara_res = evaluators_pubmedqa[name].run_cara_llm_evaluation(case, trace) # Pass full MedicalCase

            metrics = evaluators_pubmedqa[name].calculate_metrics(trace, case.gold_label)
            metrics["cara_llm_score"] = cara_res["cara_llm_score"]
            metrics["cara_llm_sd"] = cara_res["cara_llm_sd"]
            metrics["cara_llm_cost"] = cara_res["cara_llm_cost"]

    print("\nPubMedQA Evaluation Summaries:")
    summary_data_pubmedqa = []
    for name, eval_obj in evaluators_pubmedqa.items():
        res = eval_obj.get_summary()
        res['Architecture'] = name
        summary_data_pubmedqa.append(res)

    summary_df_pubmedqa = pd.DataFrame(summary_data_pubmedqa).set_index('Architecture')
    display(summary_df_pubmedqa)

except FileNotFoundError as fnf_e:
    print(f"Error: One or more PubMedQA dataset files not found. Please ensure 'ori_pqal.json' and 'test_ground_truth.json' are in the expected path. Details: {fnf_e}")
except Exception as e:
    print(f"An error occurred during PubMedQA evaluation: {e}")